version: '3.9'
services:
  webhook:
    build:
      context: .
      dockerfile:  ./docker/webhook/Dockerfile
    container_name: webhook
    ports:
     - "5000:5000"
    volumes:
      - /usr/pipe:/usr/pipe

  piclhub:
    build:
      context: .
      dockerfile: ./docker/piclhub/Dockerfile
    container_name: piclhub
    ports:
      - "80:80"

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
